### ISSUE TITLE
Ask whether vim should be installed locally if sudo is unavailable

### ISSUE THREAD

**Issue by gamesh411** [whisperity/dotfiles-framework#3]
In case the user does not have root privileges to install vim under system bin, offer to install it inside the users home.

**Comment by whisperity** [comment]
I've implemented a subfeature of this as described in #2. Basically, actions now take an `if` (or `if not`) list, in which `superuser` is a valid argument.

For example, installing `ccache` will be done like this. Superuser access will be requested. The user will press Ctrl-D because they don't have (or don't want to) install system-wide. Thus, the first `shell` call is skipped, but the second is executed. The second call is just *fluff* to test whether the required binaries are there, but other than that, the improvement is that the ccache **hooks** can still be installed if you do not have `sudo`, and *actually installing ccache* will be done however you please (i.e. asking someone with `sudo` if on a shared system).

```yaml
  - action: shell
    if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends ccache"
  - action: shell any
    if not:
      - superuser
    commands:
      - "which ccache 1>/dev/null 2>/dev/null"
      - "echo ccache: Hooks will be installed, but no 'ccache' binary on system." 
```
