### ISSUE TITLE
Add a new action for mass symlinking

### ISSUE THREAD

**Issue by Szelethus** [whisperity/dotfiles-framework#6]
It is a common pattern in packages that we symlink every file found in a `bin/` folder to `~/bin/`, as seen in https://github.com/whisperity/dotfiles/blob/master/packages/cmake/package.yaml:

```yaml
install:
  # ...
  - action: shell
    command: "cd $HOME/bin; ln -s ../opt/cmake/bin/* ."
uninstall:
  - action: shell
    command: "cd $HOME/bin; for sl in $(ls ../opt/cmake/bin); do rm -f ${sl}; done"
```

It would be great to dedicate a new command to it.
